### ISSUE TITLE
Invalid calling object

### ISSUE THREAD

**Issue by cary-smith** [que-etc/resize-observer-polyfill#20] opened 2017-09-06 14:25 UTC
First and foremost: Nice implementation!
Second: I really do not want to make a request for IE11 but.....

I have just started to use this to decouple our library from framework cycles (like $digest in angular) but have run into a small issue when hot-reloading while running locally. Due to our use of `use strict`, IE11 cannot figure out what 'this' is for the requestAnimationFrame. This does not affect the final build.

It is extremely similar to https://github.com/vuejs/vue/issues/4465

Any chance you would be willing to ensure window objects are referenced? I would make a pull request but seem unable to at the moment.

Thanks!

**Comment by finngl** [comment] 2017-09-28 11:17
I also get "Invalid calling object" in IE. For me this is not a small issue, though, since in my case it prevents the polyfill from working. I'd be very happy to see a solution soon - thanks!

**Comment by rssfrncs** [comment] 2017-10-04 13:31
Yes, i get this problem in a Vue project during development but it works flawlessly when built.

**Comment by que-etc** [comment] 2017-10-05 02:36
@paulie4, @occamsraiser, @eeeps, @marchaos

Hi guys!

First things first, I'm terribly sorry for being such an ass and ignoring all your bug tickets. I had some personal issues to deal with. Now I'm mostly back on track and I'll respond or publish a fix for all of the tickets till the beginning of the next week. 

@cary-smith, it seems that I see the problem though I don't how to reproduce it. Any ideas on how it can be done so that I can verify that the bug is fixed? Thanks.

**Comment by rssfrncs** [comment] 2017-10-05 06:13
@que-etc 

To mirror my exact setup you could scaffold a VueJS project using vue-cli.

```
npm install vue-cli -g
vue init pwa resize-bug
npm run start
```

I am able to reproduce this on demand, by using the `start` script, using the polyfill within a Vue component and viewing in IE11.

**Comment by jspath** [comment] 2017-10-10 20:59
I am also experiencing this issue in IE11 in a preact/webpack app I am working on.

Binding the window object to requestAnimationFrame in src/shims/requestAnimationFrame.js fixes it for me:
```
export default (() => {
    if (typeof requestAnimationFrame === 'function') {
        return requestAnimationFrame.bind(window);
    }

    return callback => setTimeout(() => callback(Date.now()), 1000 / 60);
})();
```

Not sure if this is an acceptable solution or not, but it does seem to work without any ill effects.

**Comment by cary-smith** [comment] 2017-11-03 14:25
@jspath is right which is also similar to the approach taken to fix the [vuejs issue](https://github.com/vuejs/vue/pull/4724/commits/ff32ad1cfec258d35b7ee50e47aecab506fab541). 

You could also use your `isBrowser` check from utility.

Any chance that could be applied?

**Comment by que-etc** [comment] 2017-11-17 10:53
@cary-smith 

I've released a patch in [v1.5.0](https://github.com/que-etc/resize-observer-polyfill/releases/tag/1.5.0). Sorry that it took me so long.

Could anyone confirm that the problem is solved?

**Comment by cary-smith** [comment] 2017-11-17 14:12
Works like a charm! Thank you for the update.

...And don't apologize for the timing. This has saved me a ton of time and IE11 will hopefully be a memory soon.

**Comment by que-etc** [comment] 2017-11-17 15:39
Closing it then.

**Closed by que-etc** 2017-11-17 15:39 UTC
Labels: bug
